module PrintMiniJS where

-- pretty-printer generated by the BNF converter

import AbsMiniJS
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)
  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])



instance Print Seq where
  prt i e = case e of
   Var id exp seq -> prPrec i 0 (concatD [doc (showString "var") , prt 0 id , doc (showString "=") , prt 0 exp , doc (showString ";") , prt 0 seq])
   Sequence stat seq -> prPrec i 0 (concatD [prt 0 stat , prt 0 seq])
   Seqstat stat -> prPrec i 0 (concatD [prt 0 stat])


instance Print Stat where
  prt i e = case e of
   ExpStat exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])
   Return exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])
   If exp stat0 stat -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stat0 , doc (showString "else") , prt 0 stat])
   While exp stat -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stat])
   BlockStat seq -> prPrec i 0 (concatD [doc (showString "{") , prt 0 seq , doc (showString "}")])


instance Print Exp where
  prt i e = case e of
   Assign exp0 exp -> prPrec i 0 (concatD [prt 8 exp0 , doc (showString "=") , prt 0 exp])
   Or exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "||") , prt 2 exp])
   And exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "&&") , prt 3 exp])
   BinaryEQ exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "==") , prt 4 exp])
   BinaryNE exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "!=") , prt 4 exp])
   BinaryLT exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "<") , prt 5 exp])
   BinaryLE exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "<=") , prt 5 exp])
   BinaryGE exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString ">=") , prt 5 exp])
   BinaryGT exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString ">") , prt 5 exp])
   BinaryAdd exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "+") , prt 6 exp])
   BinarySub exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "-") , prt 6 exp])
   BinaryMul exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "*") , prt 7 exp])
   BinaryDiv exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "/") , prt 7 exp])
   UnaryNot exp -> prPrec i 7 (concatD [doc (showString "!") , prt 7 exp])
   UnaryNeg exp -> prPrec i 7 (concatD [doc (showString "-") , prt 7 exp])
   Call exp exps -> prPrec i 7 (concatD [prt 7 exp , doc (showString "(") , prt 0 exps , doc (showString ")")])
   Record exps -> prPrec i 7 (concatD [doc (showString "{") , prt 0 exps , doc (showString "}")])
   Item id exp -> prPrec i 7 (concatD [prt 0 id , doc (showString ":") , prt 7 exp])
   Function ids seq -> prPrec i 7 (concatD [doc (showString "function") , doc (showString "(") , prt 0 ids , doc (showString ")") , doc (showString "{") , prt 0 seq , doc (showString "}")])
   String str -> prPrec i 7 (concatD [prt 0 str])
   Int n -> prPrec i 7 (concatD [prt 0 n])
   TrueLit  -> prPrec i 7 (concatD [doc (showString "true")])
   FalseLit  -> prPrec i 7 (concatD [doc (showString "false")])
   Null  -> prPrec i 7 (concatD [doc (showString "null")])
   Undef  -> prPrec i 7 (concatD [doc (showString "undefined")])
   Variable id -> prPrec i 8 (concatD [prt 0 id])
   This  -> prPrec i 8 (concatD [doc (showString "this")])
   Field exp id -> prPrec i 8 (concatD [prt 8 exp , doc (showString ".") , prt 0 id])
   Lookup exp0 exp -> prPrec i 8 (concatD [prt 8 exp0 , doc (showString "[") , prt 0 exp , doc (showString "]")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])


